<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
     mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">查看用户信息</h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_oid">OID：</label>
                        <div class="controls">
                            <input type="text" id="edit_oid" class="span4" readonly>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_createtime">注册时间：</label>
                        <div class="controls">
                            <input type="text" id="edit_createtime" class="span4" readonly>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_lastloginip">最后登录IP：</label>
                        <div class="controls">
                            <input type="text" id="edit_lastloginip" class="span4" readonly>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_platform">最后登录设备：</label>
                        <div class="controls">
                            <input type="text" id="edit_platform" class="span4" readonly>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_identity">设备IDENTITY：</label>
                        <div class="controls">
                            <input type="text" id="edit_identity" class="span4" readonly>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_language">最后使用语言：</label>
                        <div class="controls">
                            <input type="text" id="edit_language" class="span4" readonly>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData" data-loading-text="保存中...">保存</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'>关闭</button>
            </div>
        </div>
    </div>
</div>
