<div class="hero-unit hero-unit-custom hero-unit-mgdbtm clearfix" id="listFilter">
    <form class="form-horizontal">
        <div class="control-group control-group-block">
            <div class="pull-left control-item">
                <span class="control-label">ID：</span>
                <div class="controls">
                    <input id="userid" data-paramkey='id' type="number" class="form-control input-medium" op="filterCase" value=''/>
                </div>
            </div>
            <div class="pull-left control-item">
                <span class="control-label">分类：</span>
                <div class="controls">
                    <select id="filter_typeid" data-paramkey='typeid' class="input-medium select-long" op="filterCase">
                        <option value="">全部</option>
                        <?php foreach ($typeList as $type) { ?>
                            <option value="<?php echo $type['id']; ?>"><?php echo $type['title']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="pull-left control-item">
                <span class="control-label">状态：</span>
                <div class="controls">
                    <select id="status" class="input-medium select-long" op="filterCase">
                        <option value="all">全部</option>
                        <option value="0">禁用</option>
                        <option value="1">启用</option>
                    </select>
                </div>
            </div>
            <button id="searchBtn" class="mgtop5 pull-left btn btn-primary" type="button" data-loading-text="查询中...">查询</button>
        </div>
    </form>
</div>
