<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">RSS编辑</h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_namezh">中文名称：</label>
                        <div class="controls">
                            <input type="text" id="edit_namezh" placeholder="中文名称" class="span3" data-title="中文名称">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_nameen">英文名称：</label>
                        <div class="controls">
                            <input type="text" id="edit_nameen" placeholder="英文名称" class="span3" data-title="英文名称">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_rss">RSS：</label>
                        <div class="controls">
                            <input type="text" id="edit_rss" placeholder="RSS" class="span8" data-title="RSS">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled" id="groupEdit">
                        <label class="control-label" for="edit_typeid">分类：</label>
                        <div class="controls">
                            <select id="edit_typeid" data-title="分类">
                                <?php foreach ($typeList as $type) { ?>
                                    <option value="<?php echo $type['id']; ?>"><?php echo $type['title']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_status">状态：</label>
                        <div class="controls">
                            <select id="edit_status" data-title="状态">
                                <option value="0">禁用</option>
                                <option value="1">启用</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData" data-loading-text="保存中...">保存</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'>关闭</button>
            </div>
        </div>
    </div>
</div>
