<div class="modal hide fade yulong" id="editor" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
     mf="modalfix" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">推送</h4>
            </div>
            <div class="modal-body" id="detailBody" mf="modalfix">
                <form class="form-horizontal" id="listEditor">
                    <input type="hidden" id="edit_id" value="0">
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_platform">平台：</label>
                        <div class="controls">
                            <select id="edit_platform" data-title="平台">
                                <?php foreach ($platform as $key => $value) { ?>
                                    <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_cnTitle">标题（中文）：</label>
                        <div class="controls">
                            <input type="text" id="edit_cnTitle" placeholder="标题（中文）" class="span8" data-title="标题（中文）">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_cnValue">内容（中文）：</label>
                        <div class="controls">
                            <textarea rows="3" id="edit_cnValue" class="span8" data-title="内容（中文）"></textarea>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_enTitle">标题（英文）：</label>
                        <div class="controls">
                            <input type="text" id="edit_enTitle" placeholder="标题（英文）" class="span8" data-title="标题（英文）">
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_enValue">内容（英文）：</label>
                        <div class="controls">
                            <textarea rows="3" id="edit_enValue" class="span8" data-title="内容（英文）"></textarea>
                        </div>
                    </div>
                    <div class="control-group" op="editFiled">
                        <label class="control-label" for="edit_url">落地URL：</label>
                        <div class="controls">
                            <input type="text" id="edit_url" placeholder="落地URL" class="span8" data-title="落地URL">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" id="saveListData" data-loading-text="保存中...">保存</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" id='closeEditor'>关闭</button>
            </div>
        </div>
    </div>
</div>
