<!DOCTYPE HTML>
<html>
<head>
    <?php include($webConfig['layoutPath'] . '/common/meta.phtml') ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $webConfig['imgDomain']; ?>css/select2.min.css"/>
</head>
<body>
<?php include($webConfig['layoutPath'] . '/common/header.phtml') ?>
<div class="container container-main">
    <div class="row-fluid">
        <?php include($webConfig['layoutPath'] . '/common/nav.phtml') ?>
        <div class="span10">
            <div class="cont-mod">
                <div class="page-header page-header-custom">
                    <h1 class="h1-custom">
                        管理员列表
                        <button id="createData" class="btn btn-info" style="margin-left: 5px;" type="button"
                                data-toggle="modal" data-target="#editor">新建
                        </button>
                    </h1>
                </div>
                <?php include($webConfig['layoutPath'] . '/hotel/userList_filter.phtml') ?>
                <div class="cont-mod">
                    <div class="page-header page-header-custom"></div>
                    <div class="reservation">
                        <div>
                            <div class="res-table sys-table-auto">
                                <table width="100%" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>物业</th>
                                        <th>用户名</th>
                                        <th>真实姓名</th>
                                        <th>状态</th>
                                        <th>最后登录时间</th>
                                        <th>最后登录ip</th>
                                        <th>创建时间</th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody id="dataList"></tbody>
                                </table>
                            </div>
                            <div id="pageDiv" style='padding: 20px;'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include($webConfig['layoutPath'] . '/hotel/userList_edit.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/hotel/userList_permission.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/hotel/userList_service_permission.phtml'); ?>
<script type="text/javascript">
    var YP_GLOBAL_VARS = {
        checkParams: '<?php echo json_encode(Enum_Admin::getAdminUserMustInput());?>',
        listUrl: '/hotelajax/getUserList',
        createBaseUrl: '/hotelajax/createUser',
        updateBaseUrl: '/hotelajax/updateUser',
        updateTaskPermission: '/hotelajax/updateUserServicePermission',
    };
</script>
<?php include($webConfig['layoutPath'] . '/common/list_common.phtml'); ?>
<?php include($webConfig['layoutPath'] . '/common/record.phtml') ?>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_list.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/common/yp_form.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/art.js"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/lib/select2/zh-CN.js" type="text/javascript"></script>
<script src="<?php echo $webConfig['imgDomain']; ?>js/hotel/userList.js"></script>
</body>
</html>
<script id="dataList_tpl" type="text/html">
    {{each list as info i}}
    <tr dataId="{{info.id}}">
        <td type="id" data-value="{{info.id}}">{{info.id}}</td>
        <td type="hotelid" data-value="{{info.hotelId}}">{{info.hotelName}}（{{info.groupName}}）</td>
        <td type="username" data-value="{{info.userName}}">{{info.userName}}</td>
        <td type="realname" data-value="{{info.realName}}">{{info.realName}}</td>
        <td type="remark" data-value="{{info.remark}}" style="display:none;"></td>
        <td type="status" data-value="{{info.status}}">{{info.statusShow}}</td>
        <td>{{info.lastLoginTime}}</td>
        <td>{{info.lastLoginIp}}</td>
        <td>{{info.createTime}}</td>
        <td type="permission" data-value="{{info.permission}}" style="display:none;"></td>
        <td type="taskPermission" data-value="{{info.taskPermission}}" style="display:none;"></td>
        <td type="phone" data-value="{{info.phone}}" style="display: none"></td>
        <td type="email" data-value="{{info.email}}" style="display: none"></td>
        <td type="department" data-value="{{info.department}}" style="display: none"></td>
        <td type="level" data-value="{{info.level}}" style="display: none"></td>

        <td>
            <button op="editDataOne" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}">修改</button>
            <button op="editServicePermission" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}">任务权限管理</button>
            <button op="editPermission" type="button" class="btn btn-info btn-sm" data-dataid="{{info.id}}">权限管理</button>
        </td>
    </tr>
    {{/each}}
</script>
